# Extract tables from pdf

In [1]:
import pdfplumber
import pandas as pd

PDF_PATH = r"D:\PC DISAINE\toky\Perso-D\red\momo\transaction-history-20260627_111819321.pdf"  # change to your file path

all_tables = []

with pdfplumber.open(PDF_PATH) as pdf:
    for i, page in enumerate(pdf.pages):
        table = page.extract_table()
        if table:
            print(f"Page {i+1}: found table with {len(table)-1} rows")
            all_tables.append(table)

# Use first table found, or merge all
raw = all_tables[0]
df = pd.DataFrame(raw[1:], columns=raw[0])  # row 0 = headers
df.head()

Page 1: found table with 12 rows
Page 2: found table with 16 rows
Page 3: found table with 17 rows
Page 4: found table with 17 rows
Page 5: found table with 17 rows
Page 6: found table with 18 rows
Page 7: found table with 16 rows
Page 8: found table with 17 rows
Page 9: found table with 17 rows
Page 10: found table with 16 rows
Page 11: found table with 17 rows
Page 12: found table with 17 rows
Page 13: found table with 17 rows
Page 14: found table with 18 rows
Page 15: found table with 16 rows
Page 16: found table with 16 rows
Page 17: found table with 17 rows
Page 18: found table with 16 rows
Page 19: found table with 17 rows
Page 20: found table with 16 rows
Page 21: found table with 17 rows
Page 22: found table with 16 rows
Page 23: found table with 2 rows

,Transaction\nId,Status,Transaction Type,Date,From,To,Amount (RWF),Fee\n(RWF),Balance\nAfter\n(RWF)
0,28805974985,SUCCESSFUL,PAYMENT,2026-06-26 22:27:07,250795962609\nJoie Livine NYINAWUMUNTU,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,200,N/A,4602695
1,28805848805,SUCCESSFUL,PAYMENT,2026-06-26 22:15:53,250788693771\nGeorges KWIZERA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,3000,N/A,4602495
2,28805464934,SUCCESSFUL,PAYMENT,2026-06-26 21:48:09,250780745466\nEmery MANZI,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,3000,N/A,4599510
3,28805412570,SUCCESSFUL,PAYMENT,2026-06-26 21:44:28,250780489816\nEmelinne IGIHOZO,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,5000,N/A,4596525
4,28805109859,SUCCESSFUL,PAYMENT,2026-06-26 21:26:35,250781613870\nPatricia Narindra Raoel BOTO,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,5000,N/A,4591550

# Clean raw tabular data

In [2]:
headers = all_tables[0][0]
frames = []

for t in all_tables:
    rows = [row for row in t if row != headers]  # drop repeated header rows
    frames.append(pd.DataFrame(rows, columns=headers))

df = pd.concat(frames, ignore_index=True)

df = df.replace("", pd.NA)
df = df.dropna(how="any")

df = df.rename(columns={'Amount\n(RWF)': 'Amount (RWF)'})

df['Amount (RWF)'] = df['Amount (RWF)'].astype(int)

df.shape

(350, 9)

In [10]:
df["Date"] = pd.to_datetime(df["Date"], format="%Y-%m-%d %H:%M:%S")
start = pd.to_datetime("2026-06-26 00:00:00")
end   = pd.to_datetime("2026-06-26 23:59:59")

df_subset = df[(df["Date"] >= start) & (df["Date"] <= end)]
df_subset.shape

(57, 9)

# Calculate the sum of all transactions

In [11]:
# Assign +/- sign based on the type column
df_subset["Signed Amount"] = df_subset["Amount (RWF)"].where(df_subset["Transaction Type"] == "PAYMENT", -df_subset["Amount (RWF)"])

# Then sum
total_transactions = df_subset["Signed Amount"].sum()
print(total_transactions)

536300

## Total fees

In [12]:
balance_2026_06_18 = 4068990
balance_2026_06_19 = 4602695
total_actual_transactions = balance_2026_06_19 - balance_2026_06_18
print(total_actual_transactions)

533705

In [13]:
error = 0
total_fees = total_transactions - total_actual_transactions - error

print(total_fees)

2595

# Check individual transaction fee

In [14]:
df_subset = df_subset.rename(columns={'Balance\nAfter\n(RWF)': 'Balance'})
df_subset["Balance"] = df_subset["Balance"].astype("int")

In [15]:
df_subset["transaction_fee"] = df_subset["Amount (RWF)"] - ( df_subset["Balance"] - df_subset["Balance"].shift(-1) )

In [16]:
df_subset

,Transaction\nId,Status,Transaction Type,Date,From,To,Amount (RWF),Fee\n(RWF),Balance,Signed Amount,transaction_fee
0,28805974985,SUCCESSFUL,PAYMENT,2026-06-26 22:27:07,250795962609\nJoie Livine NYINAWUMUNTU,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,200,N/A,4602695,200,0.0
1,28805848805,SUCCESSFUL,PAYMENT,2026-06-26 22:15:53,250788693771\nGeorges KWIZERA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,3000,N/A,4602495,3000,15.0
2,28805464934,SUCCESSFUL,PAYMENT,2026-06-26 21:48:09,250780745466\nEmery MANZI,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,3000,N/A,4599510,3000,15.0
3,28805412570,SUCCESSFUL,PAYMENT,2026-06-26 21:44:28,250780489816\nEmelinne IGIHOZO,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,5000,N/A,4596525,5000,25.0
4,28805109859,SUCCESSFUL,PAYMENT,2026-06-26 21:26:35,250781613870\nPatricia Narindra Raoel BOTO,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,5000,N/A,4591550,5000,25.0
5,28805096927,SUCCESSFUL,PAYMENT,2026-06-26 21:26:12,250792881437\nANDRIAMIHAJA FENOHASINA\nFLORENT,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,3500,N/A,4586575,3500,17.0
6,28804457707,SUCCESSFUL,PAYMENT,2026-06-26 20:54:32,250788500369\nAline UMULISA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,2500,N/A,4583092,2500,12.0
7,28804149878,SUCCESSFUL,PAYMENT,2026-06-26 20:41:50,250788316029\nThadée TWAGIRAYEZU,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,2500,N/A,4580604,2500,12.0
8,28804083841,SUCCESSFUL,PAYMENT,2026-06-26 20:39:27,250788316029\nThadée TWAGIRAYEZU,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,15000,N/A,4578116,15000,75.0
9,28803760946,SUCCESSFUL,PAYMENT,2026-06-26 20:27:04,250798654587\nLEIGH JOYFAVOUR\nBLESSING,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,5000,N/A,4563191,5000,25.0
10,28802253624,SUCCESSFUL,PAYMENT,2026-06-26 19:37:06,250784826282\nChristella SHIMWA MUCYO,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,10500,N/A,4558216,10500,52.0
11,28801908453,SUCCESSFUL,PAYMENT,2026-06-26 19:26:48,250795044023\nRAELISON TOKINJANAHARY\nNARINDRA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,1000,N/A,4547768,1000,0.0
12,28801851702,SUCCESSFUL,PAYMENT,2026-06-26 19:25:20,250795044023\nRAELISON TOKINJANAHARY\nNARINDRA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,1000,N/A,4546768,1000,0.0
13,28801172831,SUCCESSFUL,PAYMENT,2026-06-26 19:06:45,250788300056\nInes KAYITESI,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,15000,N/A,4545768,15000,75.0
14,28800863329,SUCCESSFUL,PAYMENT,2026-06-26 18:58:32,250785460999\nValery BIZIMANA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,3500,N/A,4530843,3500,17.0
15,28800821112,SUCCESSFUL,PAYMENT,2026-06-26 18:57:34,250788589341\nMugwaneza Benigne ISHIMWE,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,27500,N/A,4527360,27500,137.0
16,28799783967,SUCCESSFUL,PAYMENT,2026-06-26 18:30:22,250783109859\nIsimbi Sarah MUGWANEZA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,10500,N/A,4499997,10500,52.0
17,28798897086,SUCCESSFUL,PAYMENT,2026-06-26 18:05:46,250788399943\nKevin MUCYO,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,2000,N/A,4489549,2000,10.0
18,28797996920,SUCCESSFUL,PAYMENT,2026-06-26 17:36:23,250788300951\nJeanne Francoise MUBIRIGI,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,5000,N/A,4487559,5000,25.0
19,28797692816,SUCCESSFUL,PAYMENT,2026-06-26 17:25:41,250792576836\nGBIA DORCAS SANDRINE,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,2000,N/A,4482584,2000,10.0
20,28797641572,SUCCESSFUL,PAYMENT,2026-06-26 17:23:40,250788307550\nAbel BUHUNGU,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,4500,N/A,4480594,4500,22.0
21,28797058180,SUCCESSFUL,PAYMENT,2026-06-26 17:02:05,250788307717\nJerôme MIHIGO KAYITERA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,14500,N/A,4476116,14500,72.0
22,28796880406,SUCCESSFUL,PAYMENT,2026-06-26 16:55:14,250783274282\nSandrine INGABIRE,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,8000,N/A,4461688,8000,40.0
23,28795907684,SUCCESSFUL,PAYMENT,2026-06-26 16:15:08,250788351431\nSolange UMUHOZA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,200,N/A,4453728,200,0.0
24,28795631520,SUCCESSFUL,PAYMENT,2026-06-26 16:03:27,250788351431\nSolange UMUHOZA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,6900,N/A,4453528,6900,34.0
25,28795152700,SUCCESSFUL,PAYMENT,2026-06-26 15:41:53,250788354387\nGATERA MARTIN RUNYINYA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,500,N/A,4446662,500,0.0
26,28795139918,SUCCESSFUL,PAYMENT,2026-06-26 15:40:52,250788354387\nGATERA MARTIN RUNYINYA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,5000,N/A,4446162,5000,25.0
27,28795058493,SUCCESSFUL,PAYMENT,2026-06-26 15:37:22,250783206460\nAloys NDAYISHIMIYE,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,500,N/A,4441187,500,0.0
29,28794549729,SUCCESSFUL,PAYMENT,2026-06-26 15:13:24,250788984888\nClaude AMANI,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,12000,N/A,4440687,12000,60.0
30,28794021989,SUCCESSFUL,PAYMENT,2026-06-26 14:48:50,250788305049\nNelson RWIGEMA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,2000,N/A,4428747,2000,10.0
31,28793942616,SUCCESSFUL,PAYMENT,2026-06-26 14:44:56,250788305291\nFatina Mukarubibi,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,170000,N/A,4426757,170000,850.0
32,28793836348,SUCCESSFUL,PAYMENT,2026-06-26 14:39:54,250787681255\nHAILU TESFAMARIAM KIROS,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,2000,N/A,4257607,2000,10.0
33,28793815360,SUCCESSFUL,PAYMENT,2026-06-26 14:39:23,250783010660\nPatrick HIGIRO,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,7000,N/A,4255617,7000,35.0
34,28791230151,SUCCESSFUL,PAYMENT,2026-06-26 12:42:44,250789291892\nEliza Rutayomba AKALIZA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,14000,N/A,4248652,14000,70.0
35,28791127558,SUCCESSFUL,PAYMENT,2026-06-26 12:38:18,250788554956\nJean de Dieu NDAYISABYE,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,2500,N/A,4234722,2500,12.0
36,28790963422,SUCCESSFUL,PAYMENT,2026-06-26 12:31:05,250784778803\nIssa NZEYIMANA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,3000,N/A,4232234,3000,15.0
37,28790415700,SUCCESSFUL,PAYMENT,2026-06-26 12:07:28,250788522286\nHélène MUKANKUSI,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,19000,N/A,4229249,19000,95.0
38,28790076815,SUCCESSFUL,PAYMENT,2026-06-26 11:51:58,250788300440\nJanvier MUSAFIRI,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,4000,N/A,4210344,4000,20.0
39,28789559341,SUCCESSFUL,PAYMENT,2026-06-26 11:27:37,250795289179\nABALI REHA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,5000,N/A,4206364,5000,25.0
40,28789525358,SUCCESSFUL,PAYMENT,2026-06-26 11:26:19,250795581047\nVELASQUEZ GARCIA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,8000,N/A,4201389,8000,40.0
41,28789343022,SUCCESSFUL,PAYMENT,2026-06-26 11:18:12,250786482886\nAngelique GASANA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,500,N/A,4193429,500,0.0
42,28789112460,SUCCESSFUL,PAYMENT,2026-06-26 11:07:35,250788885048\nTheoneste Bagirubwira,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,4000,N/A,4192929,4000,20.0
43,28789053041,SUCCESSFUL,PAYMENT,2026-06-26 11:04:37,250789198643\nYared Gebremichael GEBRU,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,6500,N/A,4188949,6500,32.0
44,28788329374,SUCCESSFUL,PAYMENT,2026-06-26 10:30:35,250783010660\nPatrick HIGIRO,38998332\nRED IKIRWA,3000,N/A,4182481,3000,15.0
46,28788239027,SUCCESSFUL,PAYMENT,2026-06-26 10:26:16,250784211758\nElsa SANO,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,9000,N/A,4179496,9000,45.0
47,28788058292,SUCCESSFUL,PAYMENT,2026-06-26 10:18:07,250788389390\nRUZIBUKA Elvis GAKUBA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,24000,N/A,4170541,24000,120.0
48,28788016664,SUCCESSFUL,PAYMENT,2026-06-26 10:16:18,250793140228\nSharon UMULISA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,5000,N/A,4146661,5000,25.0
49,28787141310,SUCCESSFUL,LAST_TRANSACTIONS,2026-06-26 09:34:35,250795573441\nRED IKIRWA FLAVOURS Ltd,N/A,0,0,4141686,0,0.0
50,28787095362,SUCCESSFUL,PAYMENT,2026-06-26 09:32:17,250796298244\nNizzam NORHAN,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,3000,N/A,4141686,3000,15.0
51,28786929516,SUCCESSFUL,PAYMENT,2026-06-26 09:24:22,250794551960\nSolomon ASfie WONDIMENEH,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,4000,N/A,4138701,4000,20.0
52,28786764677,SUCCESSFUL,PAYMENT,2026-06-26 09:16:26,250788306026\nAntoine GATERA GAKUBA\nSANA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,5500,N/A,4134721,5500,27.0
53,28786010356,SUCCESSFUL,PAYMENT,2026-06-26 08:38:19,250781414777\nNourah KAMIKAZI,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,6000,N/A,4129248,6000,30.0
54,28785689224,SUCCESSFUL,PAYMENT,2026-06-26 08:20:58,250788739198\nLinah NYAMWIZA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,4500,N/A,4123278,4500,22.0
55,28785572800,SUCCESSFUL,PAYMENT,2026-06-26 08:15:04,250788306112\nJeanine KAYIHURA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,13000,N/A,4118800,13000,65.0
56,28785560755,SUCCESSFUL,PAYMENT,2026-06-26 08:13:57,250791434137\nCIIN HIN CIIN HIN,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,24000,N/A,4105865,24000,60.0
57,28785106094,SUCCESSFUL,PAYMENT,2026-06-26 07:47:45,250796176883\nHEBIE OUMAROU,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,9000,N/A,4081925,9000,45.0
58,28784956793,SUCCESSFUL,PAYMENT,2026-06-26 07:37:40,250788554300\nAriella KAGERUKA,38998332\nRED IKIRWA\nFLAVOURS Ltd RED\nIKIRWA...,4000,N/A,4072970,4000,NaN